!
! TWO-REACTION TEST CASE
! ZDPLASKIN
!
! This test case corresponds to an Ar plasma consisting of electrons, atomic
! ions, and neutrals. The charged particles are supposed to be generated by
! direct electron impact ionization and lost by 3-body recombination.
!
! June 2008, by S Pancheshnyi
!

program test_2reac
!
! declare variables and modules
!
  use ZDPlasKin
  implicit none
  double precision, parameter :: gas_temperature  = 800.0d0, & ! gas temperature, K
                                 density_ini_nh3  = 2.01E+18,  &
								 density_ini_o2   = 1.51E+18,  &
								 density_ini_n2   = 5.66E+18,  &
								 density_ini_elec = 9.17E-02
  double precision            :: time  = 0.0d0, time_end = 1.0d-6, dtime = 1.0d-10, & ! times, s
                                 reduced_field    = 100d0 ! reduced electric field, Td
  integer                     :: i
!
! Calcurate Energy Eq. (Look at line:47)
!
  double precision, parameter :: spec_heat_ratio  = 7.d0/5.d0
!                                 heat_source      = 1.d+8
  double precision            :: elec_power_elastic_n     = 0.d0
  logical                     :: gas_heating      = .true.
!  
! print
!
  write(*,'(/,A)') 'TWO-REACTION TEST CASE'
!
! initialization of ZDPlasKin
!
  call ZDPlasKin_init()
  call ZDPlaskin_set_config(QTPLASKIN_SAVE=.false.) ! auto save in QtPlaskin format
!
! set the physical conditions of the calculation:
!     the gas temperature and the reduced electric field
!
  call ZDPlasKin_set_conditions(GAS_TEMPERATURE=gas_temperature,REDUCED_FIELD=reduced_field )
  call ZDPlasKin_set_conditions(SPEC_HEAT_RATIO=spec_heat_ratio,GAS_HEATING=gas_heating )
!
! set initial densities
!
  call ZDPlasKin_set_density( 'NH3',density_ini_nh3)
  call ZDPlasKin_set_density(  'O2',density_ini_o2)
  call ZDPlasKin_set_density(  'N2',density_ini_n2)
  call ZDPlasKin_set_density(  'e',density_ini_elec)
  call ZDPlasKin_set_density('N2^+',density_ini_elec) 
	

! print column headers and initial values
!
  write(*,'(4(A12))') 'Time_s', ( trim(species_name(i)), i = 1, species_max )
  write(*,'(4(1pe12.4))') time, density(:)
!
! time integration
!
  do while(time .lt. time_end)
  
!!!!!!!!!E/N oscillation!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!  call ZDPlasKin_set_conditions(GAS_TEMPERATURE=gas_temperature,REDUCED_FIELD=reduced_field )
!    reduced_field  = 75 + 25d0*sin(time/1d-8)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!afterglow!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!  if(time >= 1.0d-7) then
!  call ZDPlasKin_set_conditions(GAS_TEMPERATURE=gas_temperature,REDUCED_FIELD=reduced_field )
!  reduced_field  = 1
!    end if
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	
    call ZDPlasKin_timestep(time,dtime)
    time = time + dtime
    write(*, *) 'Current time is ', time
  enddo
!
! end
!
  write(*,'(/,A,$)') 'PRESS ENTER TO EXIT ...'
  read(*,*)
end program test_2reac
